# Generated by Django 3.1.1 on 2020-11-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yauctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='currency',
            field=models.CharField(choices=[('eur', 'EUR '), ('usd', 'USD'), ('gbp', 'GBP'), ('ngn', 'NGN')], default='usd', max_length=3),
        ),
    ]
